{{- if and .Values.redis.persistence.enabled (not .Values.redis.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.redis.persistence.VolumeName }}-{{ .Values.redis.fullname }}
  labels:
    app: {{ .Values.redis.fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  storageClassName: "{{ .Values.redis.persistence.storageClassName }}"
  accessModes:
    - {{ .Values.redis.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | quote }}
{{- end }}
