global:
  ingressDomain: "s059223.edu.slurm.io"

ingressShim:
  defaultIssuerName: "letsencrypt-staging"
  defaultIssuerKind: "ClusterIssuer"

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: roysbike@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx

