services:
   redis: 
     image: redis:alpine
     container_name: redis
     
   flask:
        build: .
        container_name: flask
        ports:
            - "5000:5000"
        depends_on:
            - redis