# This is a YAML-formatted file.

image: gitlab.s059223.edu.slurm.io:5555/s059223/application
imageTag: master.1
imagePullSecret: cicd-gitlab-registry

# Resources for app. Limits is the maximum number of resources that app cas use.
# And requests is resources that will be granted to the app at start time.
replicas: 2


resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  app_port: 5000
  port: 80

ingress:
  host: flask.s059223.edu.slurm.io
  IngressClass: nginx
  ClusterIssuer: letsencrypt-staging

redis:
  image: redis:7.2.0-alpine3.18
  fullname: redis
  port: 6379
  usePassword: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: true
    storageClassName: local-storage
    VolumeName: local-volume
    accessMode: ReadWriteOnce
    size: 1Gi
