# This is a YAML-formatted file.

image: gitlab.s059223.edu.slurm.io/flask/flask-app
imageTag: master.1
imagePullSecret: cicd-gitlab-registry

# Resources for app. Limits is the maximum number of resources that app cas use.
# And requests is resources that will be granted to the app at start time.
replicas: 2


resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

service:
  app_port: 5000
  port: 80

ingress:
  host: flask.s059223.edu.slurm.io
