variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - lint
  - build
  - test
  - cleanup
  - push
  - release
  - deploy
  - rollback

#  - delete

lint-docker:
  stage: lint
  allow_failure: true
#  image: hadolint/hadolint:latest-debian
  image: hadolint/hadolint:latest-alpine
  script:
    - hadolint Dockerfile

lint-helm:
  stage: lint
  image: centosadmin/kubernetes-helm:3.6.3
  script:
    - kubectl config set-cluster k8s --insecure-skip-tls-verify=true --server=$K8S_API_URL
    - kubectl config set-credentials ci --token=$K8S_CI_TOKEN
    - kubectl config set-context ci --cluster=k8s --user=ci
    - kubectl config use-context ci
    - helm lint .helm
  allow_failure: true

build:
  stage: build
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID .

test:
  stage: test
  image:
    name: docker/compose:1.29.2
    entrypoint: [""]
  script:
    - docker-compose 
        -p "$CI_PROJECT_NAME"_"$CI_PIPELINE_ID"
      up
        --abort-on-container-exit
        --exit-code-from test
        --quiet-pull

cleanup:
  stage: cleanup
  image:
    name: docker/compose:1.29.2
    entrypoint: [""]
  script:
    - docker-compose -p "$CI_PROJECT_NAME"_"$CI_PIPELINE_ID" down
  when: always

push:
  stage: push
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  only:
    - main

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:v0.1.0
  script:
    - |
      release-cli create --name "Release $CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID" --tag-name $CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID --description "Release description changelog" 
      
#--assets-link "{\"name\":\"assets\",\"url\":\"https://gitlab.s059223.edu.slurm.io/s059223/application/-/releases",\"link_type\":\"other\"}"
  only:
    - main

deploy-k8s:
  stage: deploy
  image: centosadmin/kubernetes-helm:3.6.3
  environment:
    name: production
  script:
    - kubectl config set-cluster k8s --insecure-skip-tls-verify=true --server=$K8S_API_URL
    - kubectl config set-credentials ci --token=$K8S_CI_TOKEN
    - kubectl config set-context ci --cluster=k8s --user=ci
    - kubectl config use-context ci
    - helm upgrade --install $CI_PROJECT_PATH_SLUG .helm
        --set replicas=2
        --set image=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
        --set imageTag=$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
        --set redis.enabled="true"
        --set redis.fullname="redis"
        --set redis.port="6379"
        --set redis.usePassword="false"
        --set redis.persistence.enabled="true"
        --set redis.persistence.size=1Gi
        --set redis.persistence.storageClassName="local-storage"
        --set redis.persistence.VolumeName="local-volume"
        --set resources.limits.cpu=200m
        --set resources.limits.memory=256Mi
        --set resources.requests.cpu=200m
        --set resources.requests.memory=256Mi
        --set service.app_port=5000
        --set service.port=80
        --set ingress.host=flask.s059223.edu.slurm.io
        --set ingress.IngressClass="nginx"
        --set ingress.ClusterIssuer=letsencrypt-staging
        --wait
        --timeout 300s
        --atomic
        --debug
        --namespace $CI_PROJECT_PATH_SLUG-$CI_ENVIRONMENT_NAME

  only:
    - main

rollback:
  stage: rollback
  image: centosadmin/kubernetes-helm:3.6.3
  environment:
    name: production
  script:
    - kubectl config set-cluster k8s --insecure-skip-tls-verify=true --server=$K8S_API_URL
    - kubectl config set-credentials ci --token=$K8S_CI_TOKEN
    - kubectl config set-context ci --cluster=k8s --user=ci
    - kubectl config use-context ci
    - helm rollback $CI_PROJECT_PATH_SLUG 0
        --wait
        --timeout 300s
        --debug
        --namespace $CI_PROJECT_PATH_SLUG-$CI_ENVIRONMENT_NAME

  when: manual
