services:
  redis: 
    image: redis:7.2.0-alpine3.18
#    container_name: redis
  flask-app:
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
#    ports:
#      - "5000:5000"
    depends_on:
      - redis
  test:
    image: curlimages/curl:7.88.1
    command: /bin/sh -c "sleep 10 && curl -s http://flask-app:5000/ -i -vvv"

